CREATE DATABASE TechStockDb
GO

USE TechStockDb
GO

CREATE TABLE Produto 
(
ProdutoId INT IDENTITY(1,1) PRIMARY KEY,
Nome NVARCHAR(100) NOT NULL,
Descricao NVARCHAR(MAX),
Preco DECIMAL(10,2) NOT NULL,
Quantidade INT
);
GO